name: Run PPV WTF Automation and Push Playlist

on:
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes (UTC)
  workflow_dispatch: # Optional manual trigger

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run automation script
        run: node index.js
